In [12]:
import numpy as np
from numpy.linalg import matrix_rank
from sympy import Matrix, nsimplify

D = np.array([[1,0,1,0,1],[1,1,-3,1,-1],[-2,-1,0,0,-1]])
Ds = Matrix([[1,0,1,0,1],[1,1,-3,1,-1],[-2,-1,0,0,-1]])

print(D)

print("\nRank(D)=",matrix_rank(D))

print("\nNull Space Basis for D is \n",-2*nsimplify(Ds, rational=True).nullspace()[0],"\n",-2*nsimplify(Ds, rational=True).nullspace()[1])


[[ 1  0  1  0  1]
 [ 1  1 -3  1 -1]
 [-2 -1  0  0 -1]]

Rank(D)= 3

Null Space Basis for D is 
 Matrix([[1], [-2], [-1], [-2], [0]]) 
 Matrix([[1], [0], [1], [0], [-2]])
